[package]
name = "advent-of-code-2020"
version = "0.1.0"
authors = ["John Whittington <git@jbrengineering.co.uk>"]
edition = "2018"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
regex = "1.4.2"
log = "0.4.11"
lazy_static = "1.4.0"
